### ISSUE TITLE
How to install keybow-pager

### ISSUE THREAD

**Issue by tylermc94** [stefanoborini/keybow-pager#1]
Hello, 

I am having some trouble figuring out how to install keybow-pager to my keybow. I've tried just dropping the files onto the SD card and replacing the ones that have the same name with the files from this project, but I've had no luck. It seems that doing that just makes the keybow show the default colorscheme but stops it from outputting any keypresses.

**Comment by stefanoborini** [comment]
@tylermc94 I updated the readme. Let me know if you need more info.
